# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: empresa33
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-crud-node

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2   #Esto es muy importante ya que la primera vez no lo hice y me causo error
  iamRoleStatements:  #Para especificar en que tabla se va a conectar    
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:891377163904:table/TaskTable      

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /tasks  #Cuando visite este ruta se ejecutara la funtion addTask
          method: get
  createTask:
    handler: src/addTask.addTask  # El primer src/addTask.addTask es el nombre del archivo y el segundo es el nombre de la fuction 
    events:
      - httpApi:
          path: /tasks #Cuando visite este ruta se ejecutara la funtion addTask 
          method: post
           
resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable   #Este es el nombre de la table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH